# Generated by Django 3.2.3 on 2021-05-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudiolyticUser',
        ),
    ]
